name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Stelle sicher, dass Gradle nicht "smart watched"
      ORG_GRADLE_PROJECT_org.gradle.vfs.watch: "false"
      # Für stabilere Builds auf CI
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx3g -Dfile.encoding=UTF-8'"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Installiert Android SDK Commandline Tools + akzeptiert Lizenzen
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Optional: Wrapper validieren (Schutz gegen Wrapper-Manipulation)
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Baue Debug APK (ohne Daemon, mit Logausgabe)
      - name: Build Debug
        run: ./gradlew --no-daemon --stacktrace --info clean :app:assembleDebug

      # Lade Artefakt hoch (APK)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
